apiVersion: v1
kind: ResourceQuota
metadata:
  name: limit-etudiant
  namespace: etudiant19-ns  # Remplace par ton namespace
spec:
  hard:
    pods: "3"
    requests.cpu: "400m"
    requests.memory: "400Mi"
    limits.cpu: "800m"
    limits.memory: "520Mi"
